{% set name = "pipemind" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  path: ..

  noarch: python
  script: pip install .

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=68
    - wheel
  run:
    - python >=3.10
    - pyyaml >=6.0.1
    - pydantic >=2.7
    - fastapi >=0.110
    - uvicorn >=0.30
    - typer >=0.12
    - rich >=13.7
    - networkx >=3.3
    - snakemake >=8.11
    - fastmcp >=0.4.1
    - httpx >=0.27
    - openai >=1.0.0

test:
  imports:
    - pipemind
  commands:
    - pipemind --help

  home: https://github.com/pipemind/pipemind
  dev_url: https://github.com/pipemind/pipemind
  doc_url: https://github.com/pipemind/pipemind#readme
  summary: LLM-driven, MCP-integrated, dynamically composable bioinformatics workflow system
  description: |
    PipeMind is a research prototype for LLM-driven, MCP-integrated, dynamically composable bioinformatics workflows. It imports Snakemake workflows, exposes each rule as an MCP tool, builds DAGs dynamically via I/O matching, and drives configuration through a conversational CLI.
  license: Apache-2.0
  license_family: Apache
  license_file: ../LICENSE
  identifiers:
    - biotools:pipemind
# Extra: Bioconda/Conda-forge channel info (for PR)
# To submit to Bioconda, fork https://github.com/bioconda/bioconda-recipes and add this recipe under recipes/pipemind/
# Add to meta.yaml:
extra:
  recipe-maintainers:
    - menyawino
